name: backend-test

on:
  pull_request:
    type:
      - opened
    branches: [ main ]


jobs:
  eslint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: eslint
      run:  cd backend && npm install && npm run lint 
  
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: test
      run:  cd backend && npm install && npm run test 


